services:
  fossbilling:
    image: webhostingcoop/fossbilling:latest
    env_file: ".env"
    restart: always
    ports:
      - 5080:80
    volumes:
      - fossbilling:/var/www/html
      - ./scripts/theme-start.sh:/var/www/html/themes/start.sh
      - ./submodules/fb_whc:/var/www/html/themes/fb_whc
      - ./submodules/fb_whc_admin:/var/www/html/themes/fb_whc_admin
  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: fossbilling
      MYSQL_PASSWORD: fossbilling
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  fossbilling:
  mysql:
